; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27025.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ava\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
