@echo off
@echo Alchemist > "Alchemist.rtf"
@echo Arsonist > "Arsonist.rtf"
@echo Assassin > "Assassin.rtf"
@echo Defender > "Defender.rtf"
@echo Deity > "Deity.rtf"
@echo Dryad > "Dryad.rtf"
@echo Elemental Shifter > "Elemental Shifter.rtf"
@echo Feral > "Feral.rtf"
@echo Fiend > "Fiend.rtf"
@echo Haunt > "Haunt.rtf"
@echo Hookman > "Hookman.rtf"
@echo Leach > "Leach.rtf"
@echo Loremaster > "Loremaster.rtf"
@echo Mancer > "Mancer.rtf"
@echo Nature Tap > "Nature Tap.rtf"
@echo Nomad > "Nomad.rtf"
@echo Plasma Fighter > "Plasma Fighter.rtf"
@echo Plasma Mage > "Plasma Mage.rtf"
@echo Priest > "Priest.rtf"
@echo Shaman > "Shaman.rtf"
@echo Spirit Walker > "Spirit Walker.rtf"
@echo Tribal Mage > "Tribal Mage.rtf"
@echo Warlock > "Warlock.rtf"
@echo Warrior > "Warrior.rtf"
@echo Wind Swordsman > "Wind Swordsman.rtf"
